"""empty message

Revision ID: dad7b63f2c4b
Revises: 
Create Date: 2022-04-11 07:09:38.598479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad7b63f2c4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('name', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('location', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('email', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('photo', sa.String(length=80), nullable=True))
    op.add_column('user_profiles', sa.Column('date_joined', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_profiles', sa.Column('biography', sa.String(length=255), nullable=True))
    op.drop_column('user_profiles', 'last_name')
    op.drop_column('user_profiles', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('user_profiles', 'biography')
    op.drop_column('user_profiles', 'date_joined')
    op.drop_column('user_profiles', 'photo')
    op.drop_column('user_profiles', 'email')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'name')
    # ### end Alembic commands ###
